Repository TeamFogFog/FogFog-Server, pull requests merged in 2022-11, with the labels that each got.

#10 Feat: DB 마이그레이션
  prisma/migrations/20221113082629_221113_db_migration/migration.sql
  prisma/migrations/20221113125334_add_user_column/migration.sql
  prisma/schema.prisma
Labels: 💡 feat, 👨🏻‍🍳 ganjang

#12 Feat: 에러 핸들링
  src/app.module.ts
  src/exceptions/custom.exception.ts
  src/exceptions/global.exception.ts
  src/main.ts
Labels: 💡 feat, 🧑🏼‍🚀 jobchae

#13 Fix: prettier 포맷팅 재설정
  .prettierrc
  .vscode/settings.json
  src/exceptions/custom.exception.ts
  src/exceptions/global.exception.ts
  src/utils/swagger.ts
Labels: 🧑🏼‍🚀 jobchae, 💣 fix

#15 Hotfix: areaName type string으로 변경
  prisma/migrations/20221120083203_modify_area_name_type/migration.sql
  prisma/schema.prisma
Labels: 👨🏻‍🍳 ganjang, 🛠 hotfix

#19 Feat: Sentry Slack 연결
  package.json
  src/app.module.ts
  src/exceptions/custom.exception.ts
  src/exceptions/global.exception.ts
  src/main.ts
  src/utils/webhook.interceptor.ts
  yarn.lock
Labels: 💡 feat, 🧑🏼‍🚀 jobchae

#21 Feat: base success response dto
  src/common/dto/response-success.dto.ts
Labels: 💡 feat, 🧑🏼‍🚀 jobchae

#23 Feat: success response 반환 함수
  src/utils/success.ts
Labels: 💡 feat, 🧑🏼‍🚀 jobchae

#25 Feat: 카카오 로그인 (작성중), response 가공, DB migration
  package.json
  prisma/migrations/20221123132650_add_social_id/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/response-callback.dto.ts
  src/auth/dto/signin.dto.ts
  src/common/types/response-data.type.ts
  src/config/configuration.ts
  src/exceptions/custom.exception.ts
  src/main.ts
  src/utils/success.ts
  yarn.lock
Labels: 💡 feat, 🧑🏼‍🚀 jobchae, 📖 DB

#28 Feat: jwt token 발급 로직, 인증 strategy, guard 구현
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guards/access-token.guard.ts
  src/auth/guards/index.ts
  src/auth/guards/refresh-token.guard.ts
  src/auth/strategies/access-token.strategy.ts
  src/auth/strategies/index.ts
  src/auth/strategies/refresh-token.strategy.ts
  src/common/interfaces/JwtPayload.ts
  src/common/interfaces/JwtToken.ts
  src/config/configuration.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  yarn.lock
Labels: 💡 feat, 🧑🏼‍🚀 jobchae

#30 Feat: 카카오 로그인, jwt 발급/인증 로직
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/dto/response-callback.dto.ts
  src/auth/dto/response-signin.dto.ts
  src/auth/dto/signin.dto.ts
  src/auth/guards/access-token.guard.ts
  src/auth/guards/index.ts
  src/auth/guards/refresh-token.guard.ts
  src/auth/strategies/access-token.strategy.ts
  src/auth/strategies/index.ts
  src/auth/strategies/refresh-token.strategy.ts
  src/common/dto/response-error.dto.ts
  src/common/interfaces/JwtPayload.ts
  src/common/interfaces/JwtToken.ts
  src/common/objects/gender.ts
  src/common/objects/index.ts
  src/common/objects/social.ts
  src/common/types/response-data.type.ts
  src/config/configuration.ts
  src/prisma.service.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  src/utils/convertObjectKey.ts
  src/utils/success.ts
  yarn.lock
Labels: 💡 feat, 🧑🏼‍🚀 jobchae

#34 Fix: deploy.yaml env 추가
  .github/workflows/deploy.yaml
Labels: 🧑🏼‍🚀 jobchae, 💣 fix
