Repository TeamFogFog/FogFog-Server, pull requests merged in 2023-02, with the labels that each got.

#52 Feat: 선호 지도 설정 API
  src/common/objects/responseMessages.ts
  src/users/dto/update-preferredMap.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: 💡 feat, 👨🏻‍🍳 ganjang

#51 Feat: apple 회원가입 시 apple_refresh_token 발급 후 저장 로직 추가
  .github/workflows/deploy.yaml
  .gitignore
  prisma/migrations/20230131111627_add_apple_refresh_token/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/signin.dto.ts
  src/auth/strategies/access-token.strategy.ts
  src/common/interfaces/apple-payload.interface.ts
  src/config/configuration.ts
  src/exceptions/index.ts
  src/maps/maps.controller.ts
  src/maps/maps.service.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  src/utils/error.ts
  src/utils/validation.ts
Labels: 🧑🏼‍🚀 jobchae, 💣 fix, 🙋🏻 refactor

#53 Fix: #50 빌드 에러 수정
  .github/workflows/deploy.yaml
  src/auth/auth.service.ts
  src/config/configuration.ts
  src/maps/maps.service.ts
  src/users/users.service.ts
Labels: 🚨 bug, 🧑🏼‍🚀 jobchae, 💣 fix
