Repository TeamFogFog/FogFog-Server, pull requests merged in 2023-05, with the labels that each got.

#63 Build: apple .p8 파일 생성 path 변경
  .github/workflows/deploy.yaml
Labels: 🚨 bug, 🧑🏼‍🚀 jobchae, 💣 fix

#64 Build: update actions ubuntu version
  .github/workflows/deploy.yaml
Labels: 🧑🏼‍🚀 jobchae, 💣 fix

#67 Fix: change order of build at CD pipeline
  .github/workflows/deploy.yaml
Labels: 🚨 bug, 🧑🏼‍🚀 jobchae

#68 Fix: 배포 후 .env 생성 문제 수정
  nest-cli.json
Labels: 🚨 bug, 🧑🏼‍🚀 jobchae

#70 Fix: 배포 후 .env 가 제대로 생성되지 않는 문제
  .github/workflows/deploy.yaml
Labels: 🚨 bug, 🧑🏼‍🚀 jobchae, 🛠 hotfix

#74 Feat: 회원탈퇴 API
  .github/workflows/deploy.yaml
  prisma/migrations/20230523064410_edit_updated_at_attribute/migration.sql
  prisma/schema.prisma
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/delete-user.dto.ts
  src/common/objects/responseMessages.ts
  src/config/configuration.ts
Labels: 💡 feat, 👨🏻‍🍳 ganjang, 📖 DB

#77 Fix: 회원탈퇴 API 수정
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
Labels: bug, 👨🏻‍🍳 ganjang, 💣 fix
